### ISSUE TITLE
About firebase

### ISSUE THREAD

**Issue by kalyani25-cell** [saianurag2/ParkMe#1]
What are the modules inserted in firebase?
![firebase](https://user-images.githubusercontent.com/56754044/67261993-bb9c6d80-f4c0-11e9-99d6-55346908c731.png)

**Comment by saianurag2** [comment]
Snapshot of the database. There are two tables. Parking Area stores the details of the parking lots.
![Spark database](https://user-images.githubusercontent.com/33633371/87553774-f38fb480-c6d0-11ea-8897-ecac5edec930.PNG)
